name: CD

on: push

env:
  DEPLOY_SRC: "dist/*"

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[DEPLOY]')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlzav --delete"
          SOURCE: ${{ env.DEPLOY_SRC }}
          TARGET: ${{ secrets.TARGET_FRONTEND_LANDING }}
